# Compiler and flags
CC = gcc
CFLAGS = -Wall

help:
	@echo "Targets:"
	@echo "  run    : Compile and run the C/C++ program"
	@echo "  clean  : Remove autogenerated files"
	@echo "  help   : Display this help message"

run: calc agend

calc: Calculadora/main.c
	@$(CC) $(CFLAGS) -o Calculadora/calc Calculadora/main.c
	@./Calculadora/calc

agend: Agend/main.c
	@$(CC) $(CFLAGS) -o Agend/agend Agend/main.c
	@./Agend/agend

clean:
	@rm -vf Calculadora/calc Agend/agend
